low = ["traitor", "florida_man", "paradox_clone", "cortical_borer", "obsessed"]
medium = ["changeling", "revenant", "nightmare", "slasher", "traitor/contractor", "abductor/scientist/onemanteam", "bloodsucker"]
high = ["cult", "wizard", "clock_cultist", "ninja", "cortical_borer/hivemind", "blob", "darkspawn", "bloodling", "bingle", "heretic"]
